---

- hosts: all
  become: true
  tasks:

  - name: update repository index for Fedora
    dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install httpd package
    dnf:
      name: httpd
    when: ansible_distribution == "Fedora"

  - name: add php support for httpd for Fedora
    dnf:
      name: php
    when: ansible_distribution == "Fedora"

  - name: ensure httpd is running for Fedora
    service:
      name: httpd 
      state: started
    when: ansible_distribution == "Fedora"

  - name: Open port 80 for http access for Fedora
    firewalld:
      service: http
      permanent: true
      state: enabled
    when: ansible_distribution == "Fedora"

  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
    when: ansible_distribution == "Fedora"
