---
- hosts: all
  become: true

  tasks:
  ## perform start service for mariadb
  - name: Start service mariadb if not started
    become: yes
    service:
      name: mariadb
      state: started

  ## check to see the state of the mariadb service status
  - name: Check status of mariadb service
    service_facts:
    register: service_state
  - debug:
      var: service_state.ansible_facts.services["mariadb.service"].state
