- name: install mariadb package (Ubuntu)
  tags: ubuntu,os,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb package (Fedora)
  tags: fedora,os,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Fedora"
